services:
  - type: web
    name: courseverse-backend
    runtime: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/backend-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: SERVER_PORT
        value: 10000
      - key: SPRING_CLOUD_AWS_REGION_STATIC
        value: ap-south-1
      - key: APP_AWS_S3_BUCKET_NAME
        value: courseverse-uploads
      - key: SPRING_CLOUD_AWS_CREDENTIALS_ACCESS_KEY
        sync: false
      - key: SPRING_CLOUD_AWS_CREDENTIALS_SECRET_KEY
        sync: false
      - key: APP_FIREBASE_CONFIG_FILE
        value: /etc/secrets/firebase-service-account-key.json
      - key: CORS_ALLOWED_ORIGINS
        value: https://courseverse-c9955.web.app,https://courseverse-c9955.firebaseapp.com
    autoDeploy: true
    healthCheckPath: /actuator/health
